# This always run (push and PR)

name: Java CI with Maven (Linux)

on:
  push:
    paths-ignore:
     - 'README.md'
  pull_request:
    paths-ignore:
     - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.5.0
    - name: Set up JDK 11
      uses: actions/setup-java@v3.6.0
      with:
        java-version: 11
        distribution: temurin
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2
          !~/.m2/**/*lorenzobettini*
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.target') }}
        restore-keys: ${{ runner.os }}-m2-
        # hashFiles('**/pom.xml', '**/maven.yml', '**/*.target') might be too much
        # just the .target files are not enough to invalidate the cache
    - name: Run Tycho POMless Language using our POMs
      run: mvn clean verify
      working-directory: io.github.lorenzobettini.tychotestlanguage.parent
